---

- name: Copy Filebeat config file
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat

- name: Copy Metricbeat config file
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
  notify: restart metricbeat

- name: Run Filebeat 'setup' command
  shell: "filebeat setup"
  notify: restart filebeat

- name: Run Metricbeat 'setup' command
  shell: "metricbeat setup"
  notify: restart metricbeat
