---

# the var "jenkins-project-workspace" is passed in during run-time
# eg: ansible-playbook release.yml --extra-vars "jenkins-project-workspace=/var/lib/jenkins/workspace/prov-wp-env"
ansible_ssh_private_key_file: "{{ jenkins-project-workspace }}/Project-5/Terrafrom_Jenkins_Ansible_Wordpress/Ansible/wordpress-nginx/ssh_keys/ec2-user-privatekey.pem"
