---

- name: restart elasticsearch
  shell: |
    service elasticsearch restart
    while [ `curl -s -o /dev/null -w "%{http_code}" {{ elasticsearch_url }}` != 200 ]; do echo "waiting for ES to return HTTP200 code"; sleep 5; done

- name: restart kibana
  systemd:
    name: kibana
    state: restarted

- name: restart filebeat
  systemd:
    name: filebeat
    state: restarted

- name: restart metricbeat
  systemd:
    name: metricbeat
    state: restarted
