---

- name: restart elasticsearch
  shell: |
    service elasticsearch restart
    i=0; while [ `curl -s -o /dev/null -w "%{http_code}" {{ elasticsearch_url }}` != 200 ]; do echo "waiting for ES to return HTTP200 code. Will retry for 60 secs"; sleep 5; if [ ${i} -lt 12 ]; then i=$((i+1)); else exit 5; fi; done

- name: restart kibana
  systemd:
    name: kibana
    state: restarted

- name: restart filebeat
  systemd:
    name: filebeat
    state: restarted

- name: restart metricbeat
  systemd:
    name: metricbeat
    state: restarted
