---
#- src: lrk.prometheus
- src: cloudalchemy.prometheus
- src: cloudalchemy.node-exporter
- src: cloudalchemy.grafana
- src: lean_delivery.elasticsearch
- src: lean_delivery.java
- src: lean_delivery.kibana
- src: elastic.beats
- src: robertdebock.epel
- src: geerlingguy.ansible
