---
 - name: Install Prometheus + Grafana + ElasticSearch + Kibana
   remote_user: ec2-user
   become: yes
   become_method: sudo

   hosts: all



   tasks:
     - name: Perform additional configuration tasks
       include: tasks/additional-config.yml

   handlers:
     - name: My handlers
       include: handlers/main.yml
