---
 - name: Install Prometheus + Grafana + ElasticSearch + Kibana
   remote_user: ec2-user
   become: yes
   become_method: sudo

   hosts: all

   roles:
     - role: lrk.prometheus
       vars:
          prometheus_components: [ "prometheus", "node_exporter", alertmanager]
          prometheus_version: 2.17.2
          prometheus_config_template: templates/prometheus.yml.j2
          alertmanager_version: 0.20.0
          nodeexporter_version: 0.18.1
          nodeexporter_service_name: nodeexporter
          nodeexporter_listen_port: 9113

     - role: cloudalchemy.grafana
       vars:
          grafana_security:
            admin_user: admin
            admin_password: "{{ grafana_password }}"

     - role: lean_delivery.java
       vars:
         java_package: jre
         java_major_version: 8
         transport: repositories

     - role: lean_delivery.elasticsearch
       vars:
         elastic_branch: 7

     - role: lean_delivery.kibana
       vars:
         elastic_branch: 7

     - role: elastic.beats
       vars:
         beats_version: 7.6.2
         beat: filebeat
         beat_conf:
          # default conf, this will be overridden later on in additional-config.yml
          filebeat:
            inputs:
              - type: log
                enabled: true
                paths:
                  - /var/log/*.log

     - role: elastic.beats
       vars:
         beats_version: 7.6.2
         beat: metricbeat
         # default conf, this will be overridden later on in additional-config.yml
         beat_conf:
          metricbeat:
            setup:
              ilm:
                policy_file: /etc/filebeat/policies/my-default-metricbeat.json
                overwrite: true

     - role: robertdebock.epel
     - role: geerlingguy.ansible

   tasks:
     - name: Perform additional configuration tasks
       include: tasks/additional-config.yml

   handlers:
     - name: My handlers
       include: handlers/main.yml
