---

- name: restart elasticsearch
  shell: |
    service elasticsearch restart
    i=0; while [ `curl -s -o /dev/null -w "%{http_code}" {{ elasticsearch_url }}` != 200 ]; do echo "waiting for ES to return HTTP200 code. Will retry for 60 secs"; sleep 5; if [ ${i} -lt 12 ]; then i=$((i+1)); else exit 5; fi; done

- name: restart kibana
  shell: |
    service kibana restart
    i=0; while [ `curl -s -o /dev/null -w "%{http_code}" http://{{ kibana_host }}:{{ kibana_port }}/api/status` != 200 ]; do echo "waiting for Kibana to return HTTP200 code. Will retry for 60 secs"; sleep 5; if [ ${i} -lt 12 ]; then i=$((i+1)); else exit 5; fi; done


- name: restart filebeat
  systemd:
    name: filebeat
    state: restarted

- name: restart metricbeat
  systemd:
    name: metricbeat
    state: restarted

- name: restart node_exporter
  systemd:
    name: nodeexporter_54
    state: restarted
