---
- name: Install MySql
  remote_user: ec2-user
  become: yes
  become_method: sudo

  hosts: tag_app_tier_database
  roles:
    - common
    - mysql


- name: Install WordPress, Nginx, and PHP-FPM
  remote_user: ec2-user
  become: yes
  become_method: sudo

  hosts: tag_app_tier_web
  roles:
    - common
    - nginx
    - php-fpm
    - wordpress
