---
 - name: Configure Jenkins on AMZ2
   remote_user: ec2-user
   become: yes
   become_method: sudo

   hosts: all
   roles:
    - role: lean_delivery.java
      vars:
        - java_package: jre
        - java_major_version: 8
        - transport: repositories

    - role: lean_delivery.jenkins

    - role: diodonfrost.terraform
      vars:
        - terraform_version: 0.11.14

    - role: geerlingguy.ansible

   tasks:
    - name: Install Python-Boto packages
      package:
        name: "python-boto"
        state: present

    - name: Copy Key file
      copy:
        src: ssh_keys/ec2-user-privatekey.pem
        dest: /root/ec2-user-privatekey.pem.txt
        owner: root
        group: root
        mode: '0500'
        decrypt: yes
